baseurl = "http://www.example.com"
title = "DOUGSHANNON"
theme = "coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Doug Shannon"
    info = "Developer Extraordinaire"
    description = "Doug Shannon's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "/img/doug-s.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "Enter a text here."

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/Doug-Shannon/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/WDShannon/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium fa-2x"
    weight = 3
    url = "https://medium.com/@wdouglasshannon"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/doug-shannon-41853017/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"